parameters:
#    meytip_tournament.example.class: Meytip\TournamentBundle\Example

services:
#    meytip_tournament.example:
#        class: %meytip_tournament.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
