parameters:
#    meytip_user.example.class: Meytip\UserBundle\Example

services:
#    meytip_user.example:
#        class: %meytip_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
