# quotes rest controller
acme_hello:
    type: rest
    resource: "@MeytipInnlabBundle/Resources/config/quotes_router.yml"

MeytipInnlabBundle_team:
        resource: "@MeytipInnlabBundle/Resources/config/routing/team.yml"
        prefix:   /team


MeytipInnlabBundle_quote:
        resource: "@MeytipInnlabBundle/Resources/config/routing/quote.yml"
        prefix:   /quote
        schemes:  [https]

#meytip_innlab_check:
 #   pattern:  /check
  #  defaults: { _controller: MeytipInnlabBundle:Check:check }

meytip_innlab_repair:
    pattern:  /repair
    defaults: { _controller: MeytipInnlabBundle:Check:repair }

meytip_innlab_result:
    pattern:  /result
    defaults: { _controller: MeytipInnlabBundle:Check:result}

#fos user bundle routing
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile


