parameters:
#    meytip_event.example.class: Meytip\EventBundle\Example

services:
#    meytip_event.example:
#        class: %meytip_event.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
