parameters:
    mycalc.class:      Meytip\InnlabBundle\Services\EventCalc
    myuserhelper.class: Meytip\InnlabBundle\Services\SchedHelper
    registerlistener.class: Meytip\InnlabBundle\Listener\RegistrationConfirmListener


services:
    event_calc:
        class:        "%mycalc.class%"
        arguments: ["@doctrine.orm.entity_manager"]

    user_helper_calc:
        class:     "%myuserhelper.class%"
        arguments: ["@doctrine.orm.entity_manager","@event_calc"]

    rs_user.registration_complet:
         class: %registerlistener.class%
         arguments: [@router]
         tags:
            - { name: kernel.event_subscriber }
