parameters:
    mycalc.class:      Meytip\InnlabBundle\Services\EventCalc
    myuserhelper.class: Meytip\InnlabBundle\Services\SchedHelper


services:
    event_calc:
        class:        "%mycalc.class%"
        arguments: ["@doctrine.orm.entity_manager"]

    user_helper_calc:
            class:     "%myuserhelper.class%"
            arguments: ["@doctrine.orm.entity_manager","@event_calc"]
