parameters:
#    meytip_stats.example.class: Meytip\StatsBundle\Example

services:
#    meytip_stats.example:
#        class: %meytip_stats.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
